target("vlm-dev")
    set_kind("binary")
    add_packages("eigen", "openmp")
    add_includedirs("../common")
    add_includedirs("include", {public = true})
    set_default(false)
    add_files("src/*.cpp", "../common/database/*.cpp", "dev/*.cpp")

target("vlm")
    set_kind("static")
    add_packages("eigen", "openmp")
    add_includedirs("../common")
    add_files("src/*.cpp", "../common/database/*.cpp")
    add_includedirs("include", {public = true})
