add_requires("gmsh 4.11.1")

-- target("geometrie-dev")
--     set_kind("binary")
--     add_packages("eigen", "gmsh")
--     add_includedirs("../common")
--     add_includedirs("include", {public = true})
--     add_files("src/*.cpp")
--     add_files("dev/*.cpp")

target("geometrie")
    set_kind("static")
    add_packages("eigen", "gmsh")
    add_includedirs("../common")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
