add_requires("gmsh 4.11.1")

target("geometrie-dev")
    set_kind("binary")
    set_default(false)
    add_packages("eigen", "gmsh")
    add_deps("geometrie")
    add_files("dev/*.cpp")

target("geometrie")
    set_kind("static")
    add_packages("eigen", "gmsh")
    add_includedirs("../common")
    add_files("src/*.cpp")
    add_includedirs("include", {public = true})
