 target("aero-dev")
    set_kind("binary")
    -- set_runargs("../../../../examples/conf.ini")
    add_packages("eigen", "openmp")
    add_includedirs("../common")
    add_deps("vlm", "structure", "aero")
    add_files("dev/*.cpp")

target("aero")
    set_kind("static")
    add_packages("eigen", "openmp")
    add_includedirs("../common")
    add_includedirs("include", {public = true})
    add_deps("vlm", "structure")
    add_files("src/*.cpp")
