target("rans")
    set_kind("headeronly")
    add_packages("eigen", "openmp")
    add_includedirs("../common")
    add_includedirs("include", {public = true})

target("rans-dev")
    set_kind("binary")
    set_default(false)
    add_packages("eigen", "openmp")
    add_deps("rans")
    add_includedirs("../common")
    add_files("dev/*.cpp")