target("structure-dev")
    set_kind("binary")
    set_default(false)
    add_packages("openmp", "eigen")
    add_includedirs("../common")
    add_deps("structure")
    add_files("dev/main.cpp")

target("structure")
    set_kind("headeronly")
    add_packages("openmp", "eigen")
    add_includedirs("../common")
    add_includedirs("include", {public = true})
