
IRANS_DIR := ../

multigrid:
	g++ multigrid.cpp -o multigrid -I${IRANS_DIR} -I${EIGEN_DIR} -O3 -fopenmp -DNDEBUG -march=native


custom:
	g++ custom.cpp -o custom -I${IRANS_DIR} -I${EIGEN_DIR} -O3 -fopenmp -DNDEBUG -march=native

